site_name: AIC-HCMUS Fragment Segmentation
repo_url: https://github.com/magnusdtd/AIC-HCMUS-Fragment-Segmentation
theme:
  logo: assets/ai-made-by-rock-fragment.svg
  favicon: assets/ai-made-by-rock-fragment.svg
  name: material
  features:
    - content.code.copy
    - content.code.select


nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md
  - About: about.md

plugins:
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: vi
          name: Tiếng Việt
          build: true
          nav:
            - Trang chủ: index.vi.md
            - Sử dụng: usage.vi.md
            - API: api.vi.md
            - Giới thiệu: about.vi.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
