site_name: AIC-HCMUS Fragment Segmentation
repo_url: https://github.com/magnusdtd/AIC-HCMUS-Fragment-Segmentation
theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true

        # - locale: vn
        #   name: Tiếng Việt
        #   build: true

nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md
  - About: about.md

# nav_translations:
#   vn:
#     - Trang chủ: index.md
#     - Giới thiệu: about.md
#     - Cài đặt: installation.md
#     - Sử dụng: usage.md
#     - API: api.md