site_name: AIC-HCMUS Fragment Segmentation
site_url: https://magnusdtd.github.io/AIC-HCMUS-Fragment-Segmentation/
repo_url: https://github.com/magnusdtd/AIC-HCMUS-Fragment-Segmentation
theme:
  logo: assets/ai-made-by-rock-fragment.svg
  favicon: assets/ai-made-by-rock-fragment.svg
  name: material
  features:
    - content.code.copy
    - content.code.select

plugins:
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
            - Home: index.md
            - Usage: usage.md
            - App: app.md
            - API: api.md
            - Model: model.md
            - About: about.md
        - locale: vi
          name: Tiếng Việt
          build: true
          nav:
            - Trang chủ: index.vi.md
            - Sử dụng: usage.vi.md
            - Ứng dụng: app.vi.md
            - API: api.vi.md
            - Mô hình: model.vi.md
            - Giới thiệu: about.vi.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
