site_name: AIC-HCMUS Fragment Segmentation
site_url: https://magnusdtd.github.io/AIC-HCMUS-Fragment-Segmentation/
repo_url: https://github.com/magnusdtd/AIC-HCMUS-Fragment-Segmentation
theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/ai-made-by-rock-fragment.svg
  favicon: assets/ai-made-by-rock-fragment.svg
  name: material
  features:
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - Usage: usage.md
  - App: app.md
  - API: api.md
  - Model: model.md
  - About: about.md

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
          
        - locale: vi
          name: Tiếng Việt
          build: true
          nav:
            - Trang chủ: index.vi.md
            - Sử dụng: usage.vi.md
            - Ứng dung: app.vi.md
            - Tài liệu API: api.vi.md
            - Mô hình: model.vi.md
            - Giới thiệu: about.vi.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
