apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: aic-hcmus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/aic-hcmus/app:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
        env:
        - name: DATABASE_URL
          value: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@postgres.aic-hcmus-app.svc.cluster.local:5432/mydatabase"
        - name: MINIO_URL
          value: "http://minio.aic-hcmus-app.svc.cluster.local:9000"
        - name: MINIO_ROOT_USER
          value: "{{MINIO_USER}}"
        - name: MINIO_ROOT_PASSWORD
          value: "{{MINIO_PASSWORD}}"
        - name: BASE_URL
          value: "https://aic-hcmus-noobers.duckdns.org"
        - name: GOOGLE_CLIENT_ID
          value: "793710439296-m5ufnjhel9fjmkc1g1ua4n6q3ip5hvc4.apps.googleusercontent.com"
        - name: GOOGLE_CLIENT_SECRET
          value: "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"
        - name: SECRET_KEY
          value: "{{SECRET_KEY}}"
        - name: REDIS_URL
          value: "redis://redis.aic-hcmus-app.svc.cluster.local:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: aic-hcmus-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app