apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: aic-hcmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/aic-hcmus/app:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
        env:
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: DATABASE_URL
          value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.aic-hcmus.svc.cluster.local:5432/mydatabase"
        - name: MINIO_URL
          value: "http://minio.aic-hcmus.svc.cluster.local:9000"
        - name: MINIO_ROOT_USER
          value: "${MINIO_ROOT_USER}"
        - name: MINIO_ROOT_PASSWORD
          value: "${MINIO_ROOT_PASSWORD}"
        - name: BUCKET_NAME
          value: "testing"

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: aic-hcmus
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app