# k8s/celery-exporter.yaml
apiVersion: v1
kind: Service
metadata:
  name: celery-exporter
  namespace: aic-hcmus-monitor
spec:
  ports:
    - port: 9808
  selector:
    app: celery-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-exporter
  namespace: aic-hcmus-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-exporter
  template:
    metadata:
      labels:
        app: celery-exporter
    spec:
      containers:
        - name: celery-exporter
          image: danihodovic/celery-exporter:latest
          env:
            - name: CE_BROKER_URL
              value: "redis://redis.aic-hcmus-app.svc.cluster.local:6379/0"
          ports:
            - containerPort: 9808