apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: aic-hcmus-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@postgres.aic-hcmus-app.svc.cluster.local:5432/mydatabase?sslmode=disable"
          ports:
            - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: aic-hcmus-monitor
spec:
  ports:
    - port: 9187
  selector:
    app: postgres-exporter