apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: aic-hcmus-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "redis://redis.aic-hcmus-app.svc.cluster.local:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: aic-hcmus-monitor
spec:
  ports:
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: http
  selector:
    app: redis-exporter