global:
  scrape_interval: 5s

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ['app:8080']

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: minio-job-cluster
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']

  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
    - targets: ['minio:9000']

  - job_name: minio-job-node
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: ['minio:9000']

  - job_name: minio-job-resource
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
    - targets: ['minio:9000']

  - job_name: celery
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
