{{- if and .Values.minio.enabled .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aic-hcmus-fragment-segmentation.name" . }}-minio-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "aic-hcmus-fragment-segmentation.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
{{- end }} 