{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aic-hcmus-fragment-segmentation.name" . }}-grafana
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "aic-hcmus-fragment-segmentation.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  ports:
  - port: {{ .Values.monitoring.grafana.service.port }}
    targetPort: {{ .Values.monitoring.grafana.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "aic-hcmus-fragment-segmentation.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }} 