apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aic-hcmus-fragment-segmentation.name" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "aic-hcmus-fragment-segmentation.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc }}
  DB_USER: {{ .Values.secrets.dbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}
  MINIO_USER: {{ .Values.secrets.minioUser | b64enc }}
  MINIO_PASSWORD: {{ .Values.secrets.minioPassword | b64enc }} 